#Route page accueil
index:
    path:     /accueil
    defaults:
        _controller: FestizoomAppBundle:Index:index
    methods:  [GET]

#Route liste de toutes les news
allNews:
    path:     /news
    defaults:
        _controller: FestizoomAppBundle:News:allNews
    methods:  [GET]

#Route pour récupérer les news d'une pagination
getPageNews:
    path:     /news/page/{pagNum}
    defaults:
        _controller: FestizoomAppBundle:News:NewsPage
    requirements:
        name: ([a-z0-9\-])+
        pagNum: ^[1-9](\d)*
    options:
        expose: true
    methods:  [POST]

#Route d'une news
news:
    path:     /news/{title}
    defaults:
        _controller: FestizoomAppBundle:News:news
    requirements:
        title: ([a-z0-9\-])+
    methods:  [GET]

allFestival:
    path:    /festival
    defaults:
        _controller: FestizoomAppBundle:Festival:allFestivals
    methods:  [GET]

#Route d'un festival
festival:
    path:    /festival/{name}
    defaults:
        _controller: FestizoomAppBundle:Festival:festival
    requirements:
        name: ([a-z0-9\-])+
    methods:  [GET]

#Récupérer les commentaires d'un festival associé par la page
getPageFestivals:
    path:   /festival/page/{pagNum}
    defaults:
        _controller: FestizoomAppBundle:Festival:festivalPage
    requirements:
        pagNum: ^[1-9](\d)*
    options:
        expose: true
    methods:  [POST]

#Récupérer les commentaires d'un festival associé par la page
getPageVideo:
    path:   /festival/{name}/video/page/{pagNum}
    defaults:
        _controller: FestizoomAppBundle:Video:videoPage
    requirements:
        name: ([a-z0-9\-])+
        pagNum: ^[1-9](\d)*
    options:
        expose: true
    methods:  [POST]

#Récupérer les commentaires d'un festival associé par la page
getPageCom:
    path:   /festival/{name}/comment/page/{pagNum}
    defaults:
        _controller: FestizoomAppBundle:Comment:commentPage
    requirements:
        name: ([a-z0-9\-])+
        pagNum: ^[1-9](\d)*
    options:
        expose: true
    methods:  [POST]

#Routes d'administration
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin