<?php

namespace Festizoom\AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Calcule le nombre de pages necessaire à une pagination
     * @return float
     */
    public function countNbPage($festiId) {
        $qb = $this->createQueryBuilder('com');
        $qb->select('COUNT(com)')
           ->where('com.festival = :festiId')
            ->setParameter('festiId', $festiId)
            ->andWhere('com.valid=true');
        $nbNews =
            $qb->getQuery()
                ->getSingleScalarResult();
        return ceil($nbNews/10);
    }

    /**
     * Récupère les commentaire valides de fe à mp
     * @param $fe -> la première entrée
     * @param $mp -> le nombre maximum s'entrées
     * @return array
     */
    public function getLimit($fe, $mp, $festiId) {
        $qb = $this->createQueryBuilder('com');
            $qb->where('com.festival=:festiId')
            ->setParameter('festiId', $festiId)
            ->andWhere('com.valid=true')
            ->orderBy('com.date', 'DESC')
            ->setFirstResult($fe)
            ->setMaxResults($mp);
        return $qb->getQuery()
            ->getResult();
    }
}
