<?php
namespace Festizoom\AppBundle\Repository;

/**
 * FestivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Calcule le nombre de pages necessaire à une pagination
     * @return float
     */
    public function countNbPage() {
        $qb = $this -> createQueryBuilder('fest');
        $qb -> select('COUNT(fest)');
        $nbFestivals =
            $qb -> getQuery()
                -> getSingleScalarResult();
        return ceil($nbFestivals/20);
    }

    /**
     * Récupère les news de fe à mp
     * @param $fe -> la première entrée
     * @param $mp -> le nombre maximum s'entrées
     * @return array
     */
    private function getLimit($fe, $mp) {
        $qb = $this->createQueryBuilder('a');
        $qb -> setFirstResult($fe)
            -> setMaxResults($mp);
        return $qb -> getQuery()
                   -> getResult();
    }

    /**
     * Récupère les festivals à partir du numéro de page
     * @param $num
     * @return array
     */
    public function getPageFestivals($num) {
        $firstEntry = ($num - 1) * 20;
        return $this -> getLimit($firstEntry, 20);
    }
}
