<?php

namespace Festizoom\AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupere la liste des 3 dernières news pour la page d'accueil
     * @return array
     */
    public function find3Last() {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.date', 'DESC')
           ->setMaxResults(3);
        return $qb->getQuery()
                  ->getResult();
    }

    /**
     * Calcule le nombre de pages necessaire à une pagination
     * @return float
     */
    public function countNbPage() {
        $qb = $this->createQueryBuilder('a');
        $qb->select('COUNT(a)');
        $nbNews =
         $qb->getQuery()
            ->getSingleScalarResult();
        return ceil($nbNews/8);
    }

    /**
     * Récupère les news de fe à mp
     * @param $fe -> la première entrée
     * @param $mp -> le nombre maximum s'entrées
     * @return array
     */
    public function getLimit($fe, $mp) {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.date', 'DESC')
           ->setFirstResult($fe)
           ->setMaxResults($mp);
        return $qb->getQuery()
                  ->getResult();
    }
}
