<?php

namespace Festizoom\AppBundle\Repository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Calcule le nombre de pages necessaire à une pagination
     * @return float
     */
    public function countNbPage($festiId) {
        $qb = $this->createQueryBuilder('vid');
        $qb -> select('COUNT(vid)')
            -> where('vid.festival = :festiId')
            -> setParameter('festiId', $festiId)
            -> orderBy('vid.date', 'DESC');
        $nbNews =
            $qb -> getQuery()
                -> getSingleScalarResult();
        return ceil($nbNews/1);
    }

    /**
     * Récupère les commentaire valides de fe à mp
     * @param $fe -> la première entrée
     * @param $mp -> le nombre maximum s'entrées
     * @return array
     */
    private function getLimit($fe, $mp, $festiId) {
        $qb = $this->createQueryBuilder('vid');
        $qb -> where('vid.festival=:festiId')
            -> setParameter('festiId', $festiId)
            -> orderBy('vid.date', 'DESC')
            -> setFirstResult($fe)
            -> setMaxResults($mp);
        return $qb -> getQuery()
                   -> getResult();
    }

    /**
     * Récupère les vidéos à partir du numéro de page et du festival
     * @param $num
     * @param $festivalId
     * @return array
     */
    public function getPageVideos ($num, $festivalId) {
        $firstEntry = ($num - 1) * 1;
        return $this -> getLimit($firstEntry, 1, $festivalId);
    }
}
